@startuml Class_diagram


Person <|-up- Player
Player::Elo <-up- Elo_calculator
Competition -left-* Game
Backup::SaveCompetition -up-> Competition
Backup::SavePlayer -left-> Player
Game::Winner <-left- Elo_calculator



'Definition of the person class
abstract class  Person {
    # First name : string
    # Last name : string 
    # Date of birth : string

}


'Definition of the player class
class Player {  
    + Elo : int
    + Player_id : string

    + change_elo() : void
}


'Definition the the Backup class
class Backup {
    SavePlayer() : void
    SaveCompetition() : void
}



'Definition the the Elo calculator class
Class Elo_calculator {

    - Player : Player
    - GameState : Bool

}




'Definition the the Game class
Class Game {
    - Turn : Bool
    - Player1_ID : int
    - Player2_ID : int
    - Moves : List<string>
    - Winner : int | null

    + SetMove (Move:string) : void
    + RemoveLastMove() : void

}



'Definition the the Competition class
Class Competition{
    - Name : string
    - Location : string
    - Date : string
    - GameList : List<Game>
    - PlayerList : Dictionary<Player, int>


    - AddPlayer(Player : Player)



}

'Definition the the History package
package "History"  #746f6fdd {

    
    package "Players" as Playerfolder #cdcbcbdd{

    json "Player Data" as PlayerData #eeebebdd{
        "First Name" : "",
        "Last Name": "",
        "Player id": "" ,
        "Date of Birth" :"" ,
        "Registration date" :"" ,
        "elo" : "",
        "Previous Games" : "" 

    }


'HERE IS A RELATIONNNNN-----------------------------------------
    Backup::SavePlayer --> PlayerData

    }

    package "Competitions" as CompetitionFolder #cdcbcbdd {

        artifact "Ranking.txt" <<Ranking>> #eeebebdd{

        }
        package Games as Gamefolder #eeebebdd {
        json "Game Data" as Gamedata  {
            "Player 1" : "",
            "Player 2" : "",
            "Winner" : "",
            "Moves" : ""
        }
        }
        
        
    }


'HERE IS A RELATIONNNNN-----------------------------------------

    Backup::SaveCompetition --> CompetitionFolder
}

/'
person
player
Admin 
compet 
match
'/
@enduml